### ISSUE TITLE
Context menu does not appear.

### ISSUE THREAD

**Issue by Pfeiffenrohr** [cloud-py-api/file_to_text_example#1]
I have installed the app and it also runs in the Docker container.
However, the context menu does not appear for the files.

**Comment by bigcat88** [comment]
Hello. It should only appear for files with "image/png" and "image/jpeg" mime types

**Comment by Pfeiffenrohr** [comment]
Thanks for the quick answer,
But it does't appear for png files.
![context menue](https://github.com/cloud-py-api/file_to_text_example/assets/44580842/4562afeb-9aef-4de7-94db-991c57bda689)

**Comment by bigcat88** [comment]
I will take a look at it a little bit later, and return to you with answer. Thanks you for pointing it.

**Comment by bigcat88** [comment]
should be fixed in `1.3.0` version.
